version: "3"
services:
  app:
    build: ./app
    ports:
      - "8080:8080"
      - "9464:9464"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      HTTP_USER: root
      HTTP_PASSWORD: root
    ports:
      - 8081:8081

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    depends_on:
      - app
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    restart: always

volumes:
  prometheus_data: {}
  grafana_data: {}
  redis_data: {}