{
 "title": "Prime Number Demo",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Prime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prime Number Check",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(prime_check_counter_total{job=\"prime-number-demo\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prime Number Found",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(prime_counter_total{job=\"prime-number-demo\"}[$__rate_interval])",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (process_cpu_utilization{job=\"prime-number-demo\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Event Loop Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (nodejs_event_loop_utilization{job=\"prime-number-demo\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (process_memory_usage{job=\"prime-number-demo\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(network_io_direction) (rate(system_network_io{job=\"prime-number-demo\"}[$__rate_interval]))",
     "legendFormat": "{{network_io_direction}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(http_status_code) (rate(http_server_duration_count{job=\"prime-number-demo\", net_host_port=\"8080\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Latency P90 per Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, http_status_code) (rate(http_server_duration_bucket{job=\"prime-number-demo\", net_host_port=\"8080\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(http_server_duration_bucket{job=\"prime-number-demo\", net_host_port=\"8080\"}[$__rate_interval])))",
     "legendFormat": "Max"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_duration_bucket{job=\"prime-number-demo\", net_host_port=\"8080\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(http_server_duration_bucket{job=\"prime-number-demo\", net_host_port=\"8080\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.8, sum by(le) (rate(http_server_duration_bucket{job=\"prime-number-demo\", net_host_port=\"8080\"}[$__rate_interval])))",
     "legendFormat": "P80"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_duration_bucket{job=\"prime-number-demo\", net_host_port=\"8080\"}[$__rate_interval])))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Latency P90 per Path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, http_route) (rate(http_server_duration_bucket{job=\"prime-number-demo\", net_host_port=\"8080\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}